# Generated by Django 6.0.3 on 2026-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_category_products_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Food', ' Food'), ('Cloths', ' Cloths'), ('Utensils', ' Utensils'), ('Furniture', ' Furniture')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
