# Generated by Django 6.0.3 on 2026-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_category_alter_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sku',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Food', ' Food'), ('Cloths', ' Cloths'), ('Utensils', ' Utensils'), ('Furniture', ' Furniture'), ('Cosmetics', 'Cosmetics')], max_length=100),
        ),
    ]
