# Generated by Django 6.0.3 on 2026-03-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_products_reorder_level_remove_products_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
