# Generated by Django 6.0.3 on 2026-03-30 06:46

import user_mgt.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_mgt.models.CustomUserManager()),
            ],
        ),
    ]
