# Generated by Django 6.0.3 on 2026-04-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
